### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by worldpeace-germany** [cobra18t/CobraPin#4]
Hi,

on https://pinballmakers.com/wiki/index.php?title=CobraPin you refer to 

CobraPin specific info can be found here: [CobraPin on MPF Docs](https://docs.missionpinball.org/en/dev/hardware/opp/cobrapin/index.html)

that target is broken. I guess you want to link to:

https://docs.missionpinball.org/en/latest/hardware/opp/cobrapin/index.html

Maybe can be update for future readers.

**Comment by cobra18t** [comment]
Thanks for finding that. Looks like they changed the address. Fixed.
